---
- name: Install Java, Maven, Docker, and Jenkins on Amazon Linux
  hosts: ec2
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

   - name: Ensure Python3 and pip are installed
  dnf:
    name:
      - python3
      - python3-pip
    state: present

    - name: Install Python Docker SDK
  pip:
    name: docker
    executable: pip3



    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Pull latest app image
      docker_image:
        name: subasangeeth/jenkins:v1
        tag: latest
        source: pull

    - name: Run container
      docker_container:
        name: myapp
        image: subasangeeth/jenkins:v1
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
